## Copyright 2009-2018 Tom Keffer, Matthew Wall
## Distributed under terms of GPLv3.  See LICENSE.txt for your rights.
##
## Used for the AlltimeSeasons fork at...
##   https://github.com/glennmckechnie/alltimeSeasons/
#errorCatcher Echo

<div id="history_alltime" class="plot_container" style="display:none">
 <h3>Minimum Temperature</h3>
  $min_temp_table
 <h3>Average Temperature</h3>
   $avg_temp_table
 <h3>Maximum Temperature</h3>
   $max_temp_table
 <h3>Rainfall (mm)</h3>
   $rain_table
 <h3>Days when rain fell</h3>
   $rain_days_table
</div>

